Module1 task3
htmlacademy-ecmascript/1813727-cinemaddict-15 pull request #3
Opened 2021-07-29 18:28 UTC by leann-fraoigh

Немного усложнила генерацию списков -- наверняка потом нужно будет переделывать, но пока не хотелось делать одинаковые компоненты ради нужных модификаторов.

2021-07-29 22:02 UTC, iksah requested changes

2021-07-29 22:02 UTC, iksah commented on src/main.js
> +render(HEADER, createProfileTemplate(), 'beforeend');
Давай заведем перечисление под beforeend и другие варианты.
Так будет лучше, потому что
1) Будут очевидны все варианты
2) Для потребителя функции будет не важна внутренняя имплементация - а сейчас нужно посмотреть, что внутри используется `Element.insertAdjacentHTML`, а потом проверить какие значения эта функция принимает.

https://up.htmlacademy.ru/ecmascript/15/criteries#b7

2021-07-30 13:19 UTC, leann-fraoigh commented on src/main.js
> +const FOOTER = document.querySelector('.footer');
Спасибо за ссылку! Всегда немного путалась, как именовать такие константы, теперь стало понятнее. 

Материалы на английском можно смело давать, да.

2021-08-01 16:00 UTC, leann-fraoigh commented on src/main.js
> +render(HEADER, createProfileTemplate(), 'beforeend');
Я думала о том, чтобы использовать для этого комментарии в стиле JSDoc, так: 
```
/**
 * Рендерит элемент.
 * @param {string} container - Элемент, относительно которого вставляется element.
 * @param {string} element - Добавляемый элемент.
 * @param {string="beforebegin","afterbegin", "beforeend", "afterend"} place - Место вставки element относительно container.
 */
```
Это было бы ок вместо перечисления?

2021-08-01 19:31 UTC, merged