Module2 task1
htmlacademy-ecmascript/1813727-cinemaddict-15 pull request #4
Opened 2021-08-09 17:43 UTC by leann-fraoigh

2021-08-12 06:56 UTC, iksah requested changes

2021-08-12 06:56 UTC, iksah commented on src/view/card.js
> +  const {filmInfo: {title, totalRating, poster, genres: [genre1], description, runtime, release : {date}}, userDetails: {watchlist, alreadyWatched, favorite}, comments} = card;
Опять, очень длинная строка получилась.)
Если получается длинный объект - его лучше развернуть на несколько строк и отразить структуру (при деструктуризации - тоже)
```
const {
    filmInfo: {
      title,
      totalRating,
      poster,
      genres: [genre1],
      description,
      runtime,
      release: {
        date,
      },
    },
    userDetails: {
      watchlist,
      alreadyWatched,
      favorite,
    },
    comments,
  } = card;
```

Или можно вообще разделить операции на три:
```
const {
    filmInfo,
    userDetails,
    comments,
  } = card;

  const {
    title,
    totalRating,
    poster,
    genres: [genre1],
    description,
    runtime,
    release: {
      date,
    },
  } = filmInfo;

  const {
    watchlist,
    alreadyWatched,
    favorite,
  } = userDetails;
```

Но это уже дело вкуса)

2021-08-12 06:56 UTC, iksah commented on src/view/card.js
> +  const descriptionPreview = description.length < 140 ? description : `${description.substring(0, 139)}...`;
Тут кстати я бы лучше решил вопрос через css - так надежнее, потому что ширина символов может быть разной

2021-08-12 06:56 UTC, iksah commented on src/view/comment.js
> +const relativeTime = require('dayjs/plugin/relativeTime');
Кажется можно просто вот так:
`import relativeTime from 'dayjs/plugin/relativeTime';`

2021-08-12 06:56 UTC, iksah commented on src/view/comment.js
> +  const formattedDate = Date.now() - date < 172800000 ? dayjs(date).format('YYYY/MM/DD hh:mm') : dayjs(date).fromNow();
172800000 - магическая переменная.
Лучше превратить date в дату и сравнивать их с помощью dayjs

2021-08-12 06:56 UTC, iksah commented on src/view/filter.js
> +const activeFilterClass = 'main-navigation__item--active';
Константа в UPPER_SNAKE

2021-08-12 06:56 UTC, iksah commented on src/view/filter.js
> +  return `<a href="#${name}" class="main-navigation__item ${isActive ? activeFilterClass : ''}">${capitalize(camelCaseToRegular(name))} <span class="main-navigation__item-count">${count.length}</span
Разбей шаблон на несколько строк пожалуйста

2021-08-12 06:56 UTC, iksah commented on src/view/modal.js
> +  const {filmInfo: {title, alternativeTitle, totalRating, director, writers, actors, poster, genres, description, runtime, release : {date, releaseCountry}}, userDetails: {watchlist, alreadyWatched,
Тоже очень длинная строка. Кроме того, что их неудобно читать, их неудобно и поддерживать) Ведь могут добавиться новые поля или поменяться порядок

2021-08-12 06:56 UTC, iksah commented on src/view/modal.js
> +  const activeBtnClassName = (isActive) => ( isActive ? 'film-details__control-button--active' : '');
Это функция, а значит в названии должен быть глагол - например get

2021-08-12 06:56 UTC, iksah commented on src/utils.js
> +  `${arr.join(', ')}`
join и так возвращает строку, так что можно не оборачивать её в шаблон.

2021-08-12 06:56 UTC, iksah commented on src/mock/filters.js
> +    name: filterName,
Можно кстати так
```
([name, countCards]) => ({
  name,
  count: countCards(cards),
})
```

2021-08-12 06:56 UTC, iksah commented on src/mock/card.js
> +  NAMES[getRandomInteger(0, NAMES.length - 1)]
И здесь можно использовать pickRandomElement

2021-08-12 06:56 UTC, iksah commented on src/view/profile.js
> +  }
Давай вынесем определение статуса в отдельную функцию:
```
getRatingStatus(watchedFilms) {
  const Level = {...}
    if (...) {
      return Level[0]
    }
    
    if (...) {
        ...
    }
    
    return Level[3];
}
```

Так будет легче читать функцию шаблона - она будет короче)

2021-08-12 06:56 UTC, iksah commented on src/view/card.js
> +  const {filmInfo: {title, totalRating, poster, genres: [genre1], description, runtime, release : {date}}, userDetails: {watchlist, alreadyWatched, favorite}, comments} = card;
И genre1 - не очень хорошее название.
Не совсем ясно, что именно оно означает.
Или просто назови его genre, mainGenre или firstGenre, или верни весь список и по месту назначения уже доставай первый элемент.

2021-08-16 17:48 UTC, leann-fraoigh commented on src/main.js
>  for (let i = 0; i < LIST_COMMENTED.cardsCount; i++) {
Но ведь в доп. блоках не нужно отрисовывать все карточки, только по две?

2021-08-16 17:48 UTC, leann-fraoigh commented on src/mock/card.js
> +/* eslint-disable comma-dangle */
Случайно вышло :/

2021-08-16 23:46 UTC, iksah commented on src/main.js
>  for (let i = 0; i < LIST_COMMENTED.cardsCount; i++) {
@leann-fraoigh И правда, я малость запутался) Тогда да, здесь все хорошо)

2021-08-18 20:56 UTC, merged