Module3 task1
htmlacademy-ecmascript/1813727-cinemaddict-15 pull request #5
Opened 2021-08-20 07:37 UTC by leann-fraoigh

2021-08-20 22:39 UTC, iksah commented on src/main.js
> +  const modalCloseBtn = modalComponent.getElement().querySelector('.film-details__close-btn');
давай сделаем здесь метод у класса
```
getCloseButton() {
  if (!this._element) {
    return;
  }
  return this._element..querySelector('.film-details__close-btn');
}
```

2021-08-20 23:05 UTC, iksah requested changes

2021-08-20 23:05 UTC, iksah commented on src/utils.js
> +
Надо что то сделать с длинной строкой.
Давай лучше проставим export у переменных
`export const something.`
Или поставь в конце запятую и попробуй запустить автоформат

2021-08-20 23:05 UTC, iksah commented on src/utils.js
> +  document.querySelector('body').classList.toggle('hide-overflow');
Надежнее было бы сделать не тоггл, а явно передавать вкл/выкл - чтобы в случае чего. случайно не включать его, когда пытаешься выключить.

2021-08-21 12:17 UTC, leann-fraoigh commented on src/main.js
> +  }
Спрятала, но с renderCard не получилось нормально: за ней во вьюшку пришлось бы положить функцию рендера модалки (или импортировать ее из main?..), а это, кажется, слишком :(
Может быть, в следующей домашке, когда наведу порядок в подписке на события, получится это аккуратнее решить, или лучше сейчас разобраться?

2021-08-21 12:20 UTC, leann-fraoigh commented on src/utils.js
> +
Не поняла про автоформат. 
Вообще коммент относится к строке экспорта же?

2021-08-22 15:27 UTC, leann-fraoigh commented on src/main.js
> +  }
UPD Кажется, все-таки получается, но делаю это в рамках следующего ДЗ

2021-08-22 18:03 UTC, iksah commented on src/main.js
> +  }
renderCards хорошо ложится в класс ListView :) Но пусть пока будет так, а там посмотрим)

2021-08-22 18:05 UTC, iksah commented on src/main.js
> +  const modalTriggers = cardComponent.getElement().querySelectorAll('.film-card__poster, .film-card__title, .film-card__comments');
Все равно вот эти селекторы стоило спрятать внутрь класса, но пусть пока будет так.

2021-08-22 18:09 UTC, merged