Обновление века (часть 1)
htmlacademy-ecmascript/1813727-cinemaddict-15 pull request #8
Opened 2021-09-01 21:47 UTC by leann-fraoigh

WIP Пока нет проверок при отправке формы на наличие всех компонентов комментария.

---
:mortar_board: [Обновление века (часть 1)](https://up.htmlacademy.ru/ecmascript/15/user/1813727/tasks/10)

:boom: https://htmlacademy-ecmascript.github.io/1813727-cinemaddict-15/8/

2021-09-04 09:42 UTC, iksah requested changes

2021-09-04 09:42 UTC, iksah commented on src/view/modal.js
> +        },
Я бы сделал иначе - вообще не ассайнил newComment, если его нет.
Почему? потому что модель может усложниться, и проверять нужно будет больше свойств. Намного проще проверить `!!card.newComment`, чем все свойства newComment.
Плюс само наличие такого свойства может ввести в заблуждение - может ли быть, что комментарий есть, просто он пустой?

2021-09-04 09:42 UTC, iksah commented on src/view/modal.js
> +    if (data.newComment.newCommentText || data.newComment.newCommentEmoticon) {
Вот здесь будет сложнее поддерживать, если модель комментариев усложнится

2021-09-04 09:42 UTC, iksah commented on src/view/modal.js
> +    delete data.newComment;
Вот здесь не очень хорошо, потому что пирсинг обычно не предполагает изменение данных, которые он парсит. Потенциально другой программист, не знакомый с кодом функции, может легко допустить ошибку - лучше переименовать функцию из parse в process - так мы явно обозначим, что здесь могут быть какие-либо сайд-эффекты

2021-09-04 09:42 UTC, iksah commented on src/presenter/card.js
> +      this._modalComponent.setScrollPosition(prevScrollPosition);
А что, если мы воспользуемся здесь классом Smart? Можно ведь не только обновлять данные, но и заменять их полностью - а вся механика по сохранению позиции скролла уже реализована в Smart.updateElement

2021-09-04 16:44 UTC, leann-fraoigh commented on src/view/modal.js
> +    delete data.newComment;
Тут я что-то потеряла нить событий и понимание, зачем строчка   `data = Object.assign({}, data);`. Если бы тут было const `currentData = ...`, то мы бы не меняли сами данные, и функция вполне могла бы считаться/называться просто парсингом?

2021-09-05 10:53 UTC, iksah commented on src/view/modal.js
> +    delete data.newComment;
Если мы удаляем свойство из данных, которые парятся - то это изменение данных, а значит сайд-эффект и уже не парсинг.)

Вообще парсинг обычно подразумевает функцию, которая принимает "сырое значение" - например строчку с числом, и на выходе возвращает число.

Поскольку у нас нет какого-либо "распознования", то и парсингом это лучше не называть.

Вообще есть ещё такой вариант:
Можно прямо во вью завести свойство newСomment, и обновлять модель только при сабмите комментария (тогда в данные не будет попадать недописаный комментарий)

2021-09-05 14:42 UTC, merged